# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/grymestone/nomansky2.0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/grymestone/nomansky2.0

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/grymestone/nomansky2.0/CMakeFiles /home/grymestone/nomansky2.0/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/grymestone/nomansky2.0/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named font_font

# Build rule for target.
font_font: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 font_font
.PHONY : font_font

# fast build rule for target.
font_font/fast:
	$(MAKE) -f CMakeFiles/font_font.dir/build.make CMakeFiles/font_font.dir/build
.PHONY : font_font/fast

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named png_player

# Build rule for target.
png_player: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 png_player
.PHONY : png_player

# fast build rule for target.
png_player/fast:
	$(MAKE) -f CMakeFiles/png_player.dir/build.make CMakeFiles/png_player.dir/build
.PHONY : png_player/fast

gameplay/recipes.o: gameplay/recipes.cpp.o
.PHONY : gameplay/recipes.o

# target to build an object file
gameplay/recipes.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gameplay/recipes.cpp.o
.PHONY : gameplay/recipes.cpp.o

gameplay/recipes.i: gameplay/recipes.cpp.i
.PHONY : gameplay/recipes.i

# target to preprocess a source file
gameplay/recipes.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gameplay/recipes.cpp.i
.PHONY : gameplay/recipes.cpp.i

gameplay/recipes.s: gameplay/recipes.cpp.s
.PHONY : gameplay/recipes.s

# target to generate assembly for a file
gameplay/recipes.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gameplay/recipes.cpp.s
.PHONY : gameplay/recipes.cpp.s

gameplay/rsccs/armor.o: gameplay/rsccs/armor.cpp.o
.PHONY : gameplay/rsccs/armor.o

# target to build an object file
gameplay/rsccs/armor.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gameplay/rsccs/armor.cpp.o
.PHONY : gameplay/rsccs/armor.cpp.o

gameplay/rsccs/armor.i: gameplay/rsccs/armor.cpp.i
.PHONY : gameplay/rsccs/armor.i

# target to preprocess a source file
gameplay/rsccs/armor.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gameplay/rsccs/armor.cpp.i
.PHONY : gameplay/rsccs/armor.cpp.i

gameplay/rsccs/armor.s: gameplay/rsccs/armor.cpp.s
.PHONY : gameplay/rsccs/armor.s

# target to generate assembly for a file
gameplay/rsccs/armor.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gameplay/rsccs/armor.cpp.s
.PHONY : gameplay/rsccs/armor.cpp.s

gameplay/rscentity.o: gameplay/rscentity.cpp.o
.PHONY : gameplay/rscentity.o

# target to build an object file
gameplay/rscentity.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gameplay/rscentity.cpp.o
.PHONY : gameplay/rscentity.cpp.o

gameplay/rscentity.i: gameplay/rscentity.cpp.i
.PHONY : gameplay/rscentity.i

# target to preprocess a source file
gameplay/rscentity.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gameplay/rscentity.cpp.i
.PHONY : gameplay/rscentity.cpp.i

gameplay/rscentity.s: gameplay/rscentity.cpp.s
.PHONY : gameplay/rscentity.s

# target to generate assembly for a file
gameplay/rscentity.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gameplay/rscentity.cpp.s
.PHONY : gameplay/rscentity.cpp.s

gui/inventory.o: gui/inventory.cpp.o
.PHONY : gui/inventory.o

# target to build an object file
gui/inventory.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gui/inventory.cpp.o
.PHONY : gui/inventory.cpp.o

gui/inventory.i: gui/inventory.cpp.i
.PHONY : gui/inventory.i

# target to preprocess a source file
gui/inventory.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gui/inventory.cpp.i
.PHONY : gui/inventory.cpp.i

gui/inventory.s: gui/inventory.cpp.s
.PHONY : gui/inventory.s

# target to generate assembly for a file
gui/inventory.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gui/inventory.cpp.s
.PHONY : gui/inventory.cpp.s

gui/tooltip.o: gui/tooltip.cpp.o
.PHONY : gui/tooltip.o

# target to build an object file
gui/tooltip.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gui/tooltip.cpp.o
.PHONY : gui/tooltip.cpp.o

gui/tooltip.i: gui/tooltip.cpp.i
.PHONY : gui/tooltip.i

# target to preprocess a source file
gui/tooltip.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gui/tooltip.cpp.i
.PHONY : gui/tooltip.cpp.i

gui/tooltip.s: gui/tooltip.cpp.s
.PHONY : gui/tooltip.s

# target to generate assembly for a file
gui/tooltip.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/gui/tooltip.cpp.s
.PHONY : gui/tooltip.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.cpp.s
.PHONY : main.cpp.s

screens/groundscene/boundingbox.o: screens/groundscene/boundingbox.cpp.o
.PHONY : screens/groundscene/boundingbox.o

# target to build an object file
screens/groundscene/boundingbox.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/boundingbox.cpp.o
.PHONY : screens/groundscene/boundingbox.cpp.o

screens/groundscene/boundingbox.i: screens/groundscene/boundingbox.cpp.i
.PHONY : screens/groundscene/boundingbox.i

# target to preprocess a source file
screens/groundscene/boundingbox.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/boundingbox.cpp.i
.PHONY : screens/groundscene/boundingbox.cpp.i

screens/groundscene/boundingbox.s: screens/groundscene/boundingbox.cpp.s
.PHONY : screens/groundscene/boundingbox.s

# target to generate assembly for a file
screens/groundscene/boundingbox.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/boundingbox.cpp.s
.PHONY : screens/groundscene/boundingbox.cpp.s

screens/groundscene/groundentity.o: screens/groundscene/groundentity.cpp.o
.PHONY : screens/groundscene/groundentity.o

# target to build an object file
screens/groundscene/groundentity.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/groundentity.cpp.o
.PHONY : screens/groundscene/groundentity.cpp.o

screens/groundscene/groundentity.i: screens/groundscene/groundentity.cpp.i
.PHONY : screens/groundscene/groundentity.i

# target to preprocess a source file
screens/groundscene/groundentity.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/groundentity.cpp.i
.PHONY : screens/groundscene/groundentity.cpp.i

screens/groundscene/groundentity.s: screens/groundscene/groundentity.cpp.s
.PHONY : screens/groundscene/groundentity.s

# target to generate assembly for a file
screens/groundscene/groundentity.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/groundentity.cpp.s
.PHONY : screens/groundscene/groundentity.cpp.s

screens/groundscene/groundscene.o: screens/groundscene/groundscene.cpp.o
.PHONY : screens/groundscene/groundscene.o

# target to build an object file
screens/groundscene/groundscene.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/groundscene.cpp.o
.PHONY : screens/groundscene/groundscene.cpp.o

screens/groundscene/groundscene.i: screens/groundscene/groundscene.cpp.i
.PHONY : screens/groundscene/groundscene.i

# target to preprocess a source file
screens/groundscene/groundscene.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/groundscene.cpp.i
.PHONY : screens/groundscene/groundscene.cpp.i

screens/groundscene/groundscene.s: screens/groundscene/groundscene.cpp.s
.PHONY : screens/groundscene/groundscene.s

# target to generate assembly for a file
screens/groundscene/groundscene.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/groundscene.cpp.s
.PHONY : screens/groundscene/groundscene.cpp.s

screens/groundscene/player.o: screens/groundscene/player.cpp.o
.PHONY : screens/groundscene/player.o

# target to build an object file
screens/groundscene/player.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/player.cpp.o
.PHONY : screens/groundscene/player.cpp.o

screens/groundscene/player.i: screens/groundscene/player.cpp.i
.PHONY : screens/groundscene/player.i

# target to preprocess a source file
screens/groundscene/player.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/player.cpp.i
.PHONY : screens/groundscene/player.cpp.i

screens/groundscene/player.s: screens/groundscene/player.cpp.s
.PHONY : screens/groundscene/player.s

# target to generate assembly for a file
screens/groundscene/player.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/player.cpp.s
.PHONY : screens/groundscene/player.cpp.s

screens/groundscene/tile.o: screens/groundscene/tile.cpp.o
.PHONY : screens/groundscene/tile.o

# target to build an object file
screens/groundscene/tile.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/tile.cpp.o
.PHONY : screens/groundscene/tile.cpp.o

screens/groundscene/tile.i: screens/groundscene/tile.cpp.i
.PHONY : screens/groundscene/tile.i

# target to preprocess a source file
screens/groundscene/tile.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/tile.cpp.i
.PHONY : screens/groundscene/tile.cpp.i

screens/groundscene/tile.s: screens/groundscene/tile.cpp.s
.PHONY : screens/groundscene/tile.s

# target to generate assembly for a file
screens/groundscene/tile.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/tile.cpp.s
.PHONY : screens/groundscene/tile.cpp.s

screens/groundscene/tilemanager.o: screens/groundscene/tilemanager.cpp.o
.PHONY : screens/groundscene/tilemanager.o

# target to build an object file
screens/groundscene/tilemanager.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/tilemanager.cpp.o
.PHONY : screens/groundscene/tilemanager.cpp.o

screens/groundscene/tilemanager.i: screens/groundscene/tilemanager.cpp.i
.PHONY : screens/groundscene/tilemanager.i

# target to preprocess a source file
screens/groundscene/tilemanager.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/tilemanager.cpp.i
.PHONY : screens/groundscene/tilemanager.cpp.i

screens/groundscene/tilemanager.s: screens/groundscene/tilemanager.cpp.s
.PHONY : screens/groundscene/tilemanager.s

# target to generate assembly for a file
screens/groundscene/tilemanager.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/groundscene/tilemanager.cpp.s
.PHONY : screens/groundscene/tilemanager.cpp.s

screens/screenmainmenu.o: screens/screenmainmenu.cpp.o
.PHONY : screens/screenmainmenu.o

# target to build an object file
screens/screenmainmenu.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/screenmainmenu.cpp.o
.PHONY : screens/screenmainmenu.cpp.o

screens/screenmainmenu.i: screens/screenmainmenu.cpp.i
.PHONY : screens/screenmainmenu.i

# target to preprocess a source file
screens/screenmainmenu.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/screenmainmenu.cpp.i
.PHONY : screens/screenmainmenu.cpp.i

screens/screenmainmenu.s: screens/screenmainmenu.cpp.s
.PHONY : screens/screenmainmenu.s

# target to generate assembly for a file
screens/screenmainmenu.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/screenmainmenu.cpp.s
.PHONY : screens/screenmainmenu.cpp.s

screens/screenpausemenu.o: screens/screenpausemenu.cpp.o
.PHONY : screens/screenpausemenu.o

# target to build an object file
screens/screenpausemenu.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/screenpausemenu.cpp.o
.PHONY : screens/screenpausemenu.cpp.o

screens/screenpausemenu.i: screens/screenpausemenu.cpp.i
.PHONY : screens/screenpausemenu.i

# target to preprocess a source file
screens/screenpausemenu.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/screenpausemenu.cpp.i
.PHONY : screens/screenpausemenu.cpp.i

screens/screenpausemenu.s: screens/screenpausemenu.cpp.s
.PHONY : screens/screenpausemenu.s

# target to generate assembly for a file
screens/screenpausemenu.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/screenpausemenu.cpp.s
.PHONY : screens/screenpausemenu.cpp.s

screens/solarsystem/planet.o: screens/solarsystem/planet.cpp.o
.PHONY : screens/solarsystem/planet.o

# target to build an object file
screens/solarsystem/planet.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/solarsystem/planet.cpp.o
.PHONY : screens/solarsystem/planet.cpp.o

screens/solarsystem/planet.i: screens/solarsystem/planet.cpp.i
.PHONY : screens/solarsystem/planet.i

# target to preprocess a source file
screens/solarsystem/planet.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/solarsystem/planet.cpp.i
.PHONY : screens/solarsystem/planet.cpp.i

screens/solarsystem/planet.s: screens/solarsystem/planet.cpp.s
.PHONY : screens/solarsystem/planet.s

# target to generate assembly for a file
screens/solarsystem/planet.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/solarsystem/planet.cpp.s
.PHONY : screens/solarsystem/planet.cpp.s

screens/solarsystem/solarsystem.o: screens/solarsystem/solarsystem.cpp.o
.PHONY : screens/solarsystem/solarsystem.o

# target to build an object file
screens/solarsystem/solarsystem.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/solarsystem/solarsystem.cpp.o
.PHONY : screens/solarsystem/solarsystem.cpp.o

screens/solarsystem/solarsystem.i: screens/solarsystem/solarsystem.cpp.i
.PHONY : screens/solarsystem/solarsystem.i

# target to preprocess a source file
screens/solarsystem/solarsystem.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/solarsystem/solarsystem.cpp.i
.PHONY : screens/solarsystem/solarsystem.cpp.i

screens/solarsystem/solarsystem.s: screens/solarsystem/solarsystem.cpp.s
.PHONY : screens/solarsystem/solarsystem.s

# target to generate assembly for a file
screens/solarsystem/solarsystem.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/solarsystem/solarsystem.cpp.s
.PHONY : screens/solarsystem/solarsystem.cpp.s

screens/solarsystem/spaceplayer.o: screens/solarsystem/spaceplayer.cpp.o
.PHONY : screens/solarsystem/spaceplayer.o

# target to build an object file
screens/solarsystem/spaceplayer.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/solarsystem/spaceplayer.cpp.o
.PHONY : screens/solarsystem/spaceplayer.cpp.o

screens/solarsystem/spaceplayer.i: screens/solarsystem/spaceplayer.cpp.i
.PHONY : screens/solarsystem/spaceplayer.i

# target to preprocess a source file
screens/solarsystem/spaceplayer.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/solarsystem/spaceplayer.cpp.i
.PHONY : screens/solarsystem/spaceplayer.cpp.i

screens/solarsystem/spaceplayer.s: screens/solarsystem/spaceplayer.cpp.s
.PHONY : screens/solarsystem/spaceplayer.s

# target to generate assembly for a file
screens/solarsystem/spaceplayer.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/solarsystem/spaceplayer.cpp.s
.PHONY : screens/solarsystem/spaceplayer.cpp.s

screens/solarsystem/sun.o: screens/solarsystem/sun.cpp.o
.PHONY : screens/solarsystem/sun.o

# target to build an object file
screens/solarsystem/sun.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/solarsystem/sun.cpp.o
.PHONY : screens/solarsystem/sun.cpp.o

screens/solarsystem/sun.i: screens/solarsystem/sun.cpp.i
.PHONY : screens/solarsystem/sun.i

# target to preprocess a source file
screens/solarsystem/sun.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/solarsystem/sun.cpp.i
.PHONY : screens/solarsystem/sun.cpp.i

screens/solarsystem/sun.s: screens/solarsystem/sun.cpp.s
.PHONY : screens/solarsystem/sun.s

# target to generate assembly for a file
screens/solarsystem/sun.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/solarsystem/sun.cpp.s
.PHONY : screens/solarsystem/sun.cpp.s

screens/solarsystem/sysentity.o: screens/solarsystem/sysentity.cpp.o
.PHONY : screens/solarsystem/sysentity.o

# target to build an object file
screens/solarsystem/sysentity.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/solarsystem/sysentity.cpp.o
.PHONY : screens/solarsystem/sysentity.cpp.o

screens/solarsystem/sysentity.i: screens/solarsystem/sysentity.cpp.i
.PHONY : screens/solarsystem/sysentity.i

# target to preprocess a source file
screens/solarsystem/sysentity.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/solarsystem/sysentity.cpp.i
.PHONY : screens/solarsystem/sysentity.cpp.i

screens/solarsystem/sysentity.s: screens/solarsystem/sysentity.cpp.s
.PHONY : screens/solarsystem/sysentity.s

# target to generate assembly for a file
screens/solarsystem/sysentity.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/solarsystem/sysentity.cpp.s
.PHONY : screens/solarsystem/sysentity.cpp.s

screens/spacescene.o: screens/spacescene.cpp.o
.PHONY : screens/spacescene.o

# target to build an object file
screens/spacescene.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/spacescene.cpp.o
.PHONY : screens/spacescene.cpp.o

screens/spacescene.i: screens/spacescene.cpp.i
.PHONY : screens/spacescene.i

# target to preprocess a source file
screens/spacescene.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/spacescene.cpp.i
.PHONY : screens/spacescene.cpp.i

screens/spacescene.s: screens/spacescene.cpp.s
.PHONY : screens/spacescene.s

# target to generate assembly for a file
screens/spacescene.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/spacescene.cpp.s
.PHONY : screens/spacescene.cpp.s

screens/starmap/starmap.o: screens/starmap/starmap.cpp.o
.PHONY : screens/starmap/starmap.o

# target to build an object file
screens/starmap/starmap.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/starmap/starmap.cpp.o
.PHONY : screens/starmap/starmap.cpp.o

screens/starmap/starmap.i: screens/starmap/starmap.cpp.i
.PHONY : screens/starmap/starmap.i

# target to preprocess a source file
screens/starmap/starmap.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/starmap/starmap.cpp.i
.PHONY : screens/starmap/starmap.cpp.i

screens/starmap/starmap.s: screens/starmap/starmap.cpp.s
.PHONY : screens/starmap/starmap.s

# target to generate assembly for a file
screens/starmap/starmap.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/screens/starmap/starmap.cpp.s
.PHONY : screens/starmap/starmap.cpp.s

tools/anim.o: tools/anim.cpp.o
.PHONY : tools/anim.o

# target to build an object file
tools/anim.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/tools/anim.cpp.o
.PHONY : tools/anim.cpp.o

tools/anim.i: tools/anim.cpp.i
.PHONY : tools/anim.i

# target to preprocess a source file
tools/anim.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/tools/anim.cpp.i
.PHONY : tools/anim.cpp.i

tools/anim.s: tools/anim.cpp.s
.PHONY : tools/anim.s

# target to generate assembly for a file
tools/anim.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/tools/anim.cpp.s
.PHONY : tools/anim.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... font_font"
	@echo "... game"
	@echo "... png_player"
	@echo "... rebuild_cache"
	@echo "... gameplay/recipes.o"
	@echo "... gameplay/recipes.i"
	@echo "... gameplay/recipes.s"
	@echo "... gameplay/rsccs/armor.o"
	@echo "... gameplay/rsccs/armor.i"
	@echo "... gameplay/rsccs/armor.s"
	@echo "... gameplay/rscentity.o"
	@echo "... gameplay/rscentity.i"
	@echo "... gameplay/rscentity.s"
	@echo "... gui/inventory.o"
	@echo "... gui/inventory.i"
	@echo "... gui/inventory.s"
	@echo "... gui/tooltip.o"
	@echo "... gui/tooltip.i"
	@echo "... gui/tooltip.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... screens/groundscene/boundingbox.o"
	@echo "... screens/groundscene/boundingbox.i"
	@echo "... screens/groundscene/boundingbox.s"
	@echo "... screens/groundscene/groundentity.o"
	@echo "... screens/groundscene/groundentity.i"
	@echo "... screens/groundscene/groundentity.s"
	@echo "... screens/groundscene/groundscene.o"
	@echo "... screens/groundscene/groundscene.i"
	@echo "... screens/groundscene/groundscene.s"
	@echo "... screens/groundscene/player.o"
	@echo "... screens/groundscene/player.i"
	@echo "... screens/groundscene/player.s"
	@echo "... screens/groundscene/tile.o"
	@echo "... screens/groundscene/tile.i"
	@echo "... screens/groundscene/tile.s"
	@echo "... screens/groundscene/tilemanager.o"
	@echo "... screens/groundscene/tilemanager.i"
	@echo "... screens/groundscene/tilemanager.s"
	@echo "... screens/screenmainmenu.o"
	@echo "... screens/screenmainmenu.i"
	@echo "... screens/screenmainmenu.s"
	@echo "... screens/screenpausemenu.o"
	@echo "... screens/screenpausemenu.i"
	@echo "... screens/screenpausemenu.s"
	@echo "... screens/solarsystem/planet.o"
	@echo "... screens/solarsystem/planet.i"
	@echo "... screens/solarsystem/planet.s"
	@echo "... screens/solarsystem/solarsystem.o"
	@echo "... screens/solarsystem/solarsystem.i"
	@echo "... screens/solarsystem/solarsystem.s"
	@echo "... screens/solarsystem/spaceplayer.o"
	@echo "... screens/solarsystem/spaceplayer.i"
	@echo "... screens/solarsystem/spaceplayer.s"
	@echo "... screens/solarsystem/sun.o"
	@echo "... screens/solarsystem/sun.i"
	@echo "... screens/solarsystem/sun.s"
	@echo "... screens/solarsystem/sysentity.o"
	@echo "... screens/solarsystem/sysentity.i"
	@echo "... screens/solarsystem/sysentity.s"
	@echo "... screens/spacescene.o"
	@echo "... screens/spacescene.i"
	@echo "... screens/spacescene.s"
	@echo "... screens/starmap/starmap.o"
	@echo "... screens/starmap/starmap.i"
	@echo "... screens/starmap/starmap.s"
	@echo "... tools/anim.o"
	@echo "... tools/anim.i"
	@echo "... tools/anim.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

